[package]
org = "digitalpaymentshub"
name = "payment_hub"
version = "0.0.2"
distribution = "2201.10.0"
authors = ["Ballerina"]
visibility="private"

[[dependency]]
org = "ballerinax"
name = "financial.iso20022"
version = "0.0.1"
repository = "local"
