[package]
org = "digitalpaymentshub"
name = "drivers.paynet"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "financial.iso20022"
version = "0.0.4"
repository = "local"

[[dependency]]
org = "digitalpaymentshub"
name = "drivers.util"
version = "0.0.8"
repository = "local"