[driver]
name = "ypay"
code = "MY"

[driver.inbound]
transport = "http"
host = "localhost"
port = 8100

# url of the country switch
[driver.outbound]
transport = "http"
host = "localhost"
port = 8300

# hub facing api of the driver
[driver.driver_api]
host = "localhost"
port = 9092
gateway_url = "http://localhost:9092"

[payments_hub]
base_url = "http://localhost:9100"

[ballerina.log]
level = "DEBUG"
