[driver]
name = "ypay"
code = "MY"
[driver.inbound]
transport = "http"
port = 8100
[driver.outbound]
host = "localhost"
port = 9101

[payment_hub]
baseUrl = "http://localhost:9090"

[payment_network]
baseUrl = "http://localhost:9301"