[package]
org = "digitalpaymentshub"
name = "drivers.sampledriver"
version = "0.0.1"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "digitalpaymentshub"
name = "drivers.util"
version = "0.0.14"
repository = "local"
