[package]
org = "digitalpaymentshub"
name = "drivers.sampledriver"
version = "0.0.2"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "digitalpaymentshub"
name = "drivers.util"
version = "0.0.16"
repository = "local"

[[dependency]]
org = "digitalpaymentshub"
name = "payment_hub"
repository = "local"
version = "0.0.1"
