[driver]
name = "sample_driver"
code = "SD1"

# inbound url of the driver
[driver.inbound]
transport = "tcp"
host = "localhost"
port = 8084

# url of the country switch
[driver.outbound]
transport = "tcp"
host = "localhost"
port = 8201

# hub facing api of the driver
[driver.driver_api]
host = "localhost"
port = 9090
gateway_url = "http://localhost:9090"

# url of the payments hub
[payments_hub]
base_url = "http://localhost:9100"
