[driver]
name = "xpay"
code = "LK"
[driver.inbound]
transport = "tcp"
port = 8085
[driver.outbound]
host = "localhost"
port = 9100

[payment_hub]
baseUrl = "http://localhost:9090"

[payment_network]
#baseUrl = "tcp://localhost:9200"
baseUrl = "http://localhost:9300"
