[package]
org = "digitalpaymentshub"
name = "drivers.utils"
version = "0.0.27"
distribution = "2201.10.0"

[[dependency]]
org = "digitalpaymentshub"
name = "payments_hub"
repository = "local"
version = "0.0.12"
